### ISSUE TITLE
这个比赛的数据有吗

### ISSUE THREAD

**Issue by xxllp** [FireJohnny/paipaidaiAItiaozhansai#1]

**Comment by FireJohnny** [comment]
在data_set中有初赛的


发自我的 iPhone

在 2018年9月29日，09:47，potter <notifications@github.com<mailto:notifications@github.com>> 写道：

**Comment by xxllp** [comment]
看到了，数据还算清洗的干净了。。。atec的那个比赛数据你有吗

**Comment by FireJohnny** [comment]
有 好像是1.5个g来着

发自我的 iPhone

在 2018年9月29日，10:04，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


看到了，数据还算清洗的干净了。。。atec的那个比赛数据你有吗

**Comment by xxllp** [comment]
能发我一份吗，我当时参加的是另一个比赛，现在又要做这块的东西

**Comment by FireJohnny** [comment]
我到时候看能不能上传到云盘上发给你吧


发自我的 iPhone

在 2018年9月29日，10:08，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


能发我一份吗，我当时参加的是另一个比赛，现在又要做这块的东西

**Comment by xxllp** [comment]
好的，这块的比赛是个趋势哈，未来估计还会有

**Comment by FireJohnny** [comment]
比赛这种东西吗是这样的

发自我的 iPhone

在 2018年9月29日，10:11，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


好的，这块的比赛是个趋势哈，未来估计还会有

**Comment by xxllp** [comment]
这种比赛不懂深度学习根本没法玩

**Comment by FireJohnny** [comment]
还不至于 atec那个比赛 数据太大 最初使用lightgbm做的 效果还行 后面用cnn做发现其实差不太多 加了一下其他节后后 训练过拟合极其严重 我也没找到原因 线下效果挺好的 线上非常差 一值在中旬徘徊 后期我就放弃了

发自我的 iPhone

在 2018年9月29日，10:13，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


这种比赛不懂深度学习根本没法玩

**Comment by xxllp** [comment]
。。。好吧，我也是仅仅进了复赛，大神太多了 。真实的数据实在太少了

**Comment by FireJohnny** [comment]
这种东西 先用ligbm 选出重要特征 有时候有奇效

发自我的 iPhone

在 2018年9月29日，10:13，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


这种比赛不懂深度学习根本没法玩

**Comment by xxllp** [comment]
特征太稀疏了不好选的，动不动就上千上万的

**Comment by FireJohnny** [comment]
对呀 所以是有时候 有奇效

发自我的 iPhone

在 2018年9月29日，10:19，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


特征太稀疏了不好选的，动不动就上千上万的

**Comment by xxllp** [comment]
一般都是先简单再复杂的，不过有些是太复杂了。完全搞不懂的。

**Comment by FireJohnny** [comment]
比赛吗 模型越能拟合数据 效果自然越好咯

发自我的 iPhone

在 2018年9月29日，10:24，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


一般都是先简单再复杂的，不过有些是太复杂了。完全搞不懂的。

**Comment by xxllp** [comment]
简单的模型容易过拟合的，复杂的模型也是个黑箱，最后都是做特征工程 和各种集成融合，真的是靠资源

**Comment by FireJohnny** [comment]
一个人是真的难做 我一个人就进过一次复赛 太难了 智商不够

发自我的 iPhone

在 2018年9月29日，10:27，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


简单的模型容易过拟合的，复杂的模型也是个黑箱，最后都是做特征工程 和各种集成融合，真的是靠资源

**Comment by xxllp** [comment]
哈哈，确实，有时间可以加个联系方式 一起哈。 各类比赛都可以的

**Comment by FireJohnny** [comment]
可以

发自我的 iPhone

在 2018年9月29日，10:30，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


哈哈，确实，有时间可以加个联系方式 一起哈。 各类比赛都可以的

**Comment by xxllp** [comment]
我qq 505279206

**Comment by FireJohnny** [comment]
那个 数据集 我记错了 大的不是atec的 是一个图像比赛的 atec的在 version6中有训练和测试 抱歉

发自我的 iPhone

在 2018年9月29日，10:33，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


我qq 505279206

**Comment by xxllp** [comment]
我在本地运行有报错
  File "D:/daima/xxl/paipaidaiAItiaozhansai-master/train_model.py", line 190, in <module>
    train()
  File "D:/daima/xxl/paipaidaiAItiaozhansai-master/train_model.py", line 91, in train
    model.build()
  File "D:\daima\xxl\paipaidaiAItiaozhansai-master\model_for_train\Graph_model.py", line 54, in build
    input = self.embed(self.q1)
  File "D:\daima\xxl\paipaidaiAItiaozhansai-master\model_for_train\Graph_model.py", line 45, in embed
    shape=[self.vocab,self.embed_size]),
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 488, in make_tensor_proto
    (shape_size, nparray.size))
ValueError: Too many elements provided. Needed at most 3371100, but received 6267300

**Comment by xxllp** [comment]
这个真不知道是啥原因了

**Comment by FireJohnny** [comment]
前后值不对应 值是不是统计错了


发自我的 iPhone

在 2018年10月8日，16:58，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


这个真不知道是啥原因了

**Comment by xxllp** [comment]
我没改代码呢

**Comment by FireJohnny** [comment]
我修改过了 是我的错 上传了 第一版的代码

发自我的 iPhone

在 2018年10月8日，17:02，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


我没改代码呢

**Comment by xxllp** [comment]
那能提交一个能跑的版本吗

**Comment by FireJohnny** [comment]
提交了

发自我的 iPhone

在 2018年10月8日，17:40，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


那能提交一个能跑的版本吗

**Comment by xxllp** [comment]
在cpu 环境下运行还是有点问题

**Comment by FireJohnny** [comment]
什么问题呢 我没有在cpu下跑过


发自我的 iPhone

在 2018年10月8日，23:24，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


在cpu 环境下运行还是有点问题

**Comment by xxllp** [comment]
Process finished with exit code -1073740791 (0xC0000409)

**Comment by FireJohnny** [comment]
可能是内存或者显存溢出 考虑 改小batch什么的


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: potter <notifications@github.com>
发送时间: Tuesday, October 9, 2018 8:33:58 AM
收件人: FireJohnny/paipaidaiAItiaozhansai
抄送: FireJohnny; State change
主题: Re: [FireJohnny/paipaidaiAItiaozhansai] 这个比赛的数据有吗 (#1)


Process finished with exit code -1073740791 (0xC0000409)

―

**Comment by xxllp** [comment]
我觉得不是，这也没多少数据，怎么就不足了 。

**Comment by FireJohnny** [comment]
涉及到的参数太多 很容易就溢出了 可以试一下

发自我的 iPhone

在 2018年10月9日，08:42，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


我觉得不是，这也没多少数据，怎么就不足了 。

**Comment by xxllp** [comment]
你这能跑出东西吗

**Comment by FireJohnny** [comment]
跑出啥 我都是正常跑出结果的

发自我的 iPhone

在 2018年10月9日，08:44，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


你这能跑出东西吗

**Comment by xxllp** [comment]
我看到结果了，刚才调了下batch size

**Comment by xxllp** [comment]
速度有点慢。。试试gpu

**Comment by FireJohnny** [comment]
gpu也很慢的


发自我的 iPhone

在 2018年10月9日，08:52，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


速度有点慢。。试试gpu

**Comment by FireJohnny** [comment]
把里面的lstm去掉可能好点


发自我的 iPhone

在 2018年10月9日，08:52，potter <notifications@github.com<mailto:notifications@github.com>> 写道：


速度有点慢。。试试gpu
